### ISSUE TITLE
AttributeError: 'BioCAnnotation' object has no attribute 'get_total_location'

### ISSUE THREAD

**Issue by newbietuan** [ncbi-nlp/NegBio#47]
Extracting mentions...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:08<00:00, 1171.10it/s]
Classifying mentions...
  0%|                                                                                                                                                                               | 0/10000 [00:00<?, ?it/s]BioCSentence[offset=0,text='no acute cardiopulmonary process.',infons=[parse tree=(S1 (S (S (NP (DT no) (JJ acute)) (VP (VBP cardiopulmonary) (NP (NN process)))) (. .)))],annotations=[BioCAnnotation[id=T0,text='no',infons=[tag=DT,lemma=no],locations=[BioCLocation[offset=0,length=2]],],BioCAnnotation[id=T1,text='acute',infons=[tag=JJ,lemma=acute],locations=[BioCLocation[offset=3,length=5]],],BioCAnnotation[id=T2,text='cardiopulmonary',infons=[tag=VBP,lemma=cardiopulmonary,ROOT=True],locations=[BioCLocation[offset=9,length=15]],],BioCAnnotation[id=T3,text='process',infons=[tag=NN,lemma=process],locations=[BioCLocation[offset=25,length=7]],],BioCAnnotation[id=T4,text='.',infons=[tag=.,lemma=.],locations=[BioCLocation[offset=32,length=1]],]],relations=[BioCRelation[id=R0,infons=[dependency=neg],nodes=[BioCNode[refid=T0,role=dependant],BioCNode[refid=T1,role=governor]],],BioCRelation[id=R1,infons=[dependency=nsubj],nodes=[BioCNode[refid=T1,role=dependant],BioCNode[refid=T2,role=governor]],],BioCRelation[id=R2,infons=[dependency=dobj],nodes=[BioCNode[refid=T3,role=dependant],BioCNode[refid=T2,role=governor]],],BioCRelation[id=R3,infons=[dependency=punct],nodes=[BioCNode[refid=T4,role=dependant],BioCNode[refid=T2,role=governor]],]],]
ERROR:stages.classify:Cannot parse dependency graph [offset=0]
Traceback (most recent call last):
  File "/home/mayt/chexpert-labeler/stages/classify.py", line 39, in detect
    g = semgraph.load(sentence)
  File "/home/mayt/.local/lib/python3.6/site-packages/negbio/neg/semgraph.py", line 26, in load
    loc = ann.get_total_location()
AttributeError: 'BioCAnnotation' object has no attribute 'get_total_location'

it happende in :
![4e36fbd01533ff0db6ed91965a31e21](https://user-images.githubusercontent.com/48993553/144351313-020aba9c-d036-45d7-85e0-c68ce7287853.png)
![a0ed7b13cf83ef879a4cc0cd2514e8a](https://user-images.githubusercontent.com/48993553/144351344-05781da0-a45e-460a-adb4-b24d6b1b1896.png)
![0b4f0ed261aa5c89ad7e9ce79645277](https://user-images.githubusercontent.com/48993553/144351567-a6b57f61-6637-4eb9-b6b3-e65e6405e9cd.png)

Do you know the cause of the error？ thank you very much

**Comment by newbietuan** [comment]
according to the source code, in extract.py，used bioc library，but it seems the bioc library does not have a get_total_location function。
![image](https://user-images.githubusercontent.com/48993553/144377655-2edc5b7d-aa2c-42d3-8019-dfd9e0d76aae.png)

**Comment by newbietuan** [comment]
compare to negbio2(https://github.com/yfpeng/negbio2), it seems worked by replaced 'ann.get_total_location()' by 'ann.total_span'.
